// supabase-svelte/src/components/game/Score.svelte
<script>
  import { gameData } from "../../stores";
  $: team0 = $gameData.score["team 0"];
  $: team1 = $gameData.score["team 1"];
</script>

<div class="score-panel bg-gunmetal">
  <div class="teams-info" id="teams-info">
    <div class="container row">
      <div class="col-left">
        <div class="cell">Values</div>
        <div class="cell">Kills</div>
        <div class="cell">Deaths</div>
        <div class="cell">Metal</div>
        <div class="cell">Energy</div>
      </div>
      <div class="col-middle">
        {#if team0}
          <div class="cell">Team 0</div>
          <div class="cell">{team0.kills}</div>
          <div class="cell">{team0.deaths}</div>
          <div class="cell">{team0.metal}</div>
          <div class="cell">{team0.energy}</div>
        {/if}
      </div>
      <div class="col-middle">
        {#if team0}
          <div class="cell">Team 1</div>
          <div class="cell">{team1.kills}</div>
          <div class="cell">{team1.deaths}</div>
          <div class="cell">{team1.metal}</div>
          <div class="cell">{team1.energy}</div>
        {/if}
      </div>
    </div>
  </div>
</div>

<style>

  .teams-info {
    margin: 2%;
  }

  .score-panel {
    font-size: small;
    color: #BBB
  }

  .container {
    width: 100%;
    height: 100%;
    border: 0;
    margin: 0;
    display: flex;
  }

  .row {
    flex-direction: row;
  }

  .cell {
    margin: -15%;
  }

  .col-left {
    width: 33%;
    height: 100%;
    border-collapse: collapse;
    border: 0;
    margin: 0;
    float: left;
    white-space: nowrap;
  }

  .col-middle {
    width: 33%;
    height: 100%;
    border-collapse: collapse;
    border: 0;
    margin: 0;
    float: left;
    white-space: nowrap;
  }
</style>

// frontend/src/components/home/Score.jsx
import React from 'react'

const Score = (props) => {

    return (
        <div className="score-panel">
                        <div className="teams-info" id="teams-info">
                                <div className="container row">
                                    <div className="col-left">
                                        <div className="cell">Values</div>
                                        <div className="cell">Kills</div>
                                        <div className="cell">Deaths</div>
                                        <div className="cell">Metal</div>
                                        <div className="cell">Energy</div>
                                    </div>
                                    <div className="col-middle">
                                        <div className="cell">Team 0</div>
                                        <div className="cell" id='team0-kills'>{props.score['team 0'].kills}</div>
                                        <div className="cell" id='team0-deaths'>{props.score['team 0'].deaths}</div>
                                        <div className="cell" id='team0-metal'>{props.score['team 0'].metal}</div>
                                        <div className="cell" id='team0-energy'>{props.score['team 0'].energy}</div>
                                    </div>
                                    <div className="col-right">
                                        <div className="cell">Team 1</div>
                                        <div className="cell" id='team1-kills'>{props.score['team 1'].kills}</div>
                                        <div className="cell" id='team1-deaths'>{props.score['team 1'].deaths}</div>
                                        <div className="cell" id='team1-metal'>{props.score['team 1'].metal}</div>
                                        <div className="cell" id='team1-energy'>{props.score['team 1'].energy}</div>
                                    </div>
                                </div>
                        </div>
                    </div>

    )
}

export default Score
